// <auto-generated />
using System;
using KMCM_PruebaTecnica.kmcm_models.kmcm_DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KMCM_PruebaTecnica.Migrations
{
    [DbContext(typeof(Kmcm_DbContext))]
    [Migration("20241004023750_secondMigration")]
    partial class secondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KMCM_PruebaTecnica.kmcm_models.Kmcm_person", b =>
                {
                    b.Property<int>("kmcm_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_PERSON");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("kmcm_id"));

                    b.Property<string>("kmcm_address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("ADDRESS");

                    b.Property<DateTime>("kmcm_birthdate")
                        .HasColumnType("date")
                        .HasColumnName("BIRTHDATE");

                    b.Property<string>("kmcm_lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("LASTNAME");

                    b.Property<string>("kmcm_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NAME");

                    b.Property<string>("kmcm_phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("PHONE");

                    b.HasKey("kmcm_id")
                        .HasName("PK__Persons__ID_PERSON");

                    b.ToTable("Persons", (string)null);
                });

            modelBuilder.Entity("KMCM_PruebaTecnica.kmcm_models.kmcm_user", b =>
                {
                    b.Property<int>("kmcm_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_USER");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("kmcm_id"));

                    b.Property<string>("kmcm_password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("PASSWORD");

                    b.Property<int>("kmcm_person_id")
                        .HasColumnType("int");

                    b.Property<string>("kmcm_username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USERNAME");

                    b.HasKey("kmcm_id")
                        .HasName("PK__Users__ID_USER");

                    b.HasIndex("kmcm_person_id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("KMCM_PruebaTecnica.kmcm_models.kmcm_user", b =>
                {
                    b.HasOne("KMCM_PruebaTecnica.kmcm_models.Kmcm_person", "Kmcm_person")
                        .WithMany()
                        .HasForeignKey("kmcm_person_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_Person");

                    b.Navigation("Kmcm_person");
                });
#pragma warning restore 612, 618
        }
    }
}
